### ISSUE TITLE
Deployment of kerberos/kerberos:latest fails

### ISSUE THREAD

**Issue by lexustec** [kerberos-io/docker#33]
Hello folks,

I tried to deploy kerberos on my docker swarm the last days.

I run into the same issue someone had posted on kerberos/machinery:

2021-02-03 08:28:09,527 CRIT Set uid to user 
2021-02-03 08:28:09,556 INFO RPC interface 'supervisor' initialized
2021-02-03 08:28:09,557 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2021-02-03 08:28:09,557 INFO supervisord started with pid 29
2021-02-03 08:28:10,562 INFO spawned: 'nginx' with pid 32
2021-02-03 08:28:10,567 INFO spawned: 'machinery' with pid 33
2021-02-03 08:28:10,796 INFO exited: machinery (exit status 255; not expected)
2021-02-03 08:28:11,798 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-02-03 08:28:11,801 INFO spawned: 'machinery' with pid 40
2021-02-03 08:28:11,982 INFO exited: machinery (exit status 255; not expected)
2021-02-03 08:28:13,990 INFO spawned: 'machinery' with pid 43
2021-02-03 08:28:14,196 INFO exited: machinery (exit status 255; not expected)
2021-02-03 08:28:17,203 INFO spawned: 'machinery' with pid 46
2021-02-03 08:28:17,403 INFO exited: machinery (exit status 255; not expected)
2021-02-03 08:28:18,405 INFO gave up: machinery entered FATAL state, too many start retries too quickly

also the web IF gives back a 502 bad gateway ofc.

Any hint on this ?

I tried to attach to the container but this times out.

Is it because the container is not privileged ?  ( in Docker swarm env there are no priviledged containers... if i dont fork and recompile.... ) 

Why i use docker swarm: 
Multiple endpoints ( raspi4 over WAN ) with cams ( in raspi4 local network ) and central storage/ management and routing.

**Comment by edgarGracia** [comment]
This happened to me too.
I managed to solve it by enabling the raspberry camera on the raspi-config:

`sudo raspi-config `->  Interface Options  ->  Camera

**Comment by yllekz** [comment]
This project/app/repo seems to be dead/inactive unfortunately. Not sure what's going on.

If it helps, this is my docker-compose which works on a Pi (assuming you have a directly-attached Pi camera via the camera port:

```
---
version: "2"
services:
  kerberos:
    image: kerberos/kerberos:latest
    container_name: kerberos
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /path/to/config/kerberos/capture:/etc/opt/kerberosio/capture
      - /path/to/config/kerberos/config:/etc/opt/kerberosio/config
      - /path/to/config/kerberos/logs:/etc/opt/kerberosio/logs
      - /path/to/config/kerberos/webconfig:/var/www/web/config
    ports:
      - 8080:80 #WebUI
      - 8889:8889 #kerberos comm port
    devices:
       - "/dev/vchiq:/dev/vchiq"
    privileged: true
    restart: unless-stopped
```
